name: cleverpush_example
description: Demonstrates how to use the cleverpush plugin.
version: 1.0.0+3

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  cleverpush_flutter:
    path: ../

flutter:
  uses-material-design: true
