kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: cirrusci/flutter:stable
  pull: if-not-exists
  commands:
  - flutter packages get
  - flutter analyze
  - |
    mkdir -p ~/.pub-cache

    cat <<EOF > ~/.pub-cache/credentials.json
    {
      "accessToken":"$FLUTTER_ACCESS_TOKEN",
      "refreshToken":"$FLUTTER_REFRESH_TOKEN",
      "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
      "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
      "expiration":1628761447180
    }
    EOF
  - flutter pub publish -f
  environment:
    FLUTTER_ACCESS_TOKEN:
      from_secret: FLUTTER_ACCESS_TOKEN
    FLUTTER_REFRESH_TOKEN:
      from_secret: FLUTTER_REFRESH_TOKEN
  when:
    event:
    - tag
