name: cleverpush_flutter
description: CleverPush
version: 1.9.0
homepage: https://github.com/cleverpush/cleverpush-flutter-sdk

flutter:
  plugin:
    androidPackage: com.cleverpush.flutter
    pluginClass: CleverPushPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'
